### ISSUE TITLE
how to configure Fmask?

### ISSUE THREAD

**Issue by j08lue** [DHI-GRAS/fmaskilicious#3]
I have no clue which parameters we can pass to `/usr/GERS/Fmask_4_0/application/run_Fmask_4_0.sh`. Our `run_fmask.sh` entrypoint script passes any options on - but which are there? 

I tried to run the docker image interactively and `/usr/GERS/Fmask_4_0/application/run_Fmask_4_0.sh --help` etc, but that fails for some technical reasons, at least on my first brief attempts.

**Comment by dionhaefner** [comment]
This is supposedly it:

https://github.com/GERSL/Fmask/issues/1

**Comment by j08lue** [comment]
```
Fmask_4_0 4 6 1 50
```
😬

**Comment by j08lue** [comment]
The parameters are listed in the README run example, so I think we can close this.

```bash
$ docker run \
    -v /path/to/safe:/mnt/input-dir:ro \
    -v /path/to/output:/mnt/output-dir:rw \
    -it fmask \
    S2A_MSIL1C_20180624T103021_N0206_R108_T33UUB_20180624T160117 *T33UUB* \
    [cloud_buffer_distance] [shadow_buffer_distance] \
    [snow_buffer_distance] [cloud_prob_threshold]
```
